#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="${HERE}/usr/lib/plugins"
export QT_DEBUG_PLUGINS=1
exec "${HERE}/usr/bin/Draftsman" "$@"
